version: '3.9'

services:

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - db
    hostname: app
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_DB: data
      POSTGRES_PASSWORD: postgres
    ports:
      - 8001:80
    networks:
      - my-network
    volumes:
      - ./app:/docker-app

  db:
    image: postgres:latest
    container_name: postgres
    hostname: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: data
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - 54321:5432
    networks:
      - my-network

  loader:
    build:
      context: ./loader
      dockerfile: Dockerfile
    entrypoint: ['/app/entrypoint.sh']
    container_name: loader
    depends_on:
      - db
    networks:
      - my-network
    volumes:
      - ./data:/app/data
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_DB: data
      POSTGRES_PASSWORD: postgres

networks:
  my-network:
    driver: bridge
